require("jop.plugins-setup")
require("jop.core.options")
require("jop.core.keymaps")
require("jop.core.colorscheme")
require("jop.plugins.comment")
require("jop.plugins.nvim-tree")
require("jop.plugins.lualine")
require("jop.plugins.telescope")
require("jop.plugins.nvim-cmp")
require("jop.plugins.lsp.mason")
require("jop.plugins.lsp.lspsaga")
require("jop.plugins.lsp.lspconfig")
require("jop.plugins.lsp.null-ls")
require("jop.plugins.autopairs")
require("jop.plugins.treesitter")
require("jop.plugins.gitsigns")

vim.g.python3_host_prog = "/Users/jopderidder/.config/nvim/venv/bin/python3"
